name: Keepa Slack Notifier

on:
  # ↓ 毎時 30 分に実行（日本時間）
  schedule:
    - cron: '30 * * * *'
  # 手動実行もできるように
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Slack Notifier
        env:
          KEEPA_API_KEY: ${{ secrets.KEEPA_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python profit_bot.py
