name: Keepa Slack Notifier

on:
  schedule:
    - cron: '*/30 * * * *'  # 毎時30分おきに実行（日本時間で調整される）
  workflow_dispatch:        # 手動実行も可能

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Slack Notifier
        run: python profit_bot.py
        env:
          KEEPA_API_KEY: ${{ secrets.KEEPA_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
